### ISSUE TITLE
gulp ReferenceError: primordials is not defined

### ISSUE THREAD

**Issue by alberttwong** [leggetter/devrelometer#3]
```
atwong@Alberts-MacBook-Pro devrelometer % npm install -g jspm
npm install -g gulp-cli
npm install
npm WARN deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
npm WARN deprecated ipfs-grpc-protocol@0.7.0: js-IPFS has been deprecated in favour of Helia - please see https://github.com/ipfs/js-ipfs/issues/4336 for details
npm WARN deprecated ipfs-client@0.9.2: js-IPFS has been deprecated in favour of Helia - please see https://github.com/ipfs/js-ipfs/issues/4336 for details
npm WARN deprecated ipfs-grpc-client@0.12.0: js-IPFS has been deprecated in favour of Helia - please see https://github.com/ipfs/js-ipfs/issues/4336 for details
npm WARN deprecated ipfs-core-utils@0.17.0: js-IPFS has been deprecated in favour of Helia - please see https://github.com/ipfs/js-ipfs/issues/4336 for details
npm WARN deprecated ipfs-core-types@0.13.0: js-IPFS has been deprecated in favour of Helia - please see https://github.com/ipfs/js-ipfs/issues/4336 for details
npm WARN deprecated ipfs-http-client@59.0.0: js-IPFS has been deprecated in favour of Helia - please see https://github.com/ipfs/js-ipfs/issues/4336 for details

changed 307 packages in 13s

31 packages are looking for funding
  run `npm fund` for details
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated

added 268 packages in 8s

10 packages are looking for funding
  run `npm fund` for details
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated natives@1.1.6: This module relies on Node.js's internals and will break at some point. Do not use it, and update to graceful-fs@4.x.
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
npm WARN deprecated core-js@1.2.7: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated gulp-util@2.2.20: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
npm WARN deprecated core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.

added 639 packages, and audited 640 packages in 14s

9 packages are looking for funding
  run `npm fund` for details

35 vulnerabilities (1 low, 1 moderate, 24 high, 9 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues possible (including breaking changes), run:
  npm audit fix --force

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
atwong@Alberts-MacBook-Pro devrelometer % gulp
ReferenceError: primordials is not defined
    at fs.js:42:5
    at req_ (/Users/atwong/sandbox/alberttwong.github.io/devrelometer/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/Users/atwong/sandbox/alberttwong.github.io/devrelometer/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/Users/atwong/sandbox/alberttwong.github.io/devrelometer/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
atwong@Alberts-MacBook-Pro devrelometer %
```

**Comment by alberttwong** [comment]
I tried node 8 and 11 which can get past the gulp error but the widget doesn't show up.

**Comment by alberttwong** [comment]
moved back to node 11

```
atwong@Alberts-MacBook-Pro devrelometer % gulp build-dist
[20:57:07] Using gulpfile ~/sandbox/alberttwong.github.io/devrelometer/gulpfile.js
[20:57:07] Starting 'copy-assets'...
[20:57:07] Finished 'copy-assets' after 61 ms
[20:57:07] Starting 'build-dist'...
gulp-jspm: Error: Error on translate for src/main.js at file:///Users/atwong/sandbox/alberttwong.github.io/devrelometer/src/main.js
	(SystemJS) ENOENT: no such file or directory, open '/Users/atwong/sandbox/alberttwong.github.io/devrelometer/jspm_packages/npm/babel-core@5.8.35.js'
	Error: ENOENT: no such file or directory, open '/Users/atwong/sandbox/alberttwong.github.io/devrelometer/jspm_packages/npm/babel-core@5.8.35.js'
	Error loading /Users/atwong/sandbox/alberttwong.github.io/devrelometer/jspm_packages/npm/babel-core@5.8.35.js
	Unable to load transpiler to transpile /Users/atwong/sandbox/alberttwong.github.io/devrelometer/src/main.js
    at /Users/atwong/sandbox/alberttwong.github.io/devrelometer/node_modules/systemjs-builder/lib/trace.js:496:10
    at /Users/atwong/sandbox/alberttwong.github.io/devrelometer/node_modules/systemjs-builder/lib/trace.js:455:8
    at /Users/atwong/sandbox/alberttwong.github.io/devrelometer/node_modules/systemjs-builder/lib/trace.js:421:6
    at Trace.getLoadRecord (/Users/atwong/sandbox/alberttwong.github.io/devrelometer/node_modules/systemjs-builder/lib/trace.js:151:4)
    at Trace.getAllLoadRecords (/Users/atwong/sandbox/alberttwong.github.io/devrelometer/node_modules/systemjs-builder/lib/trace.js:647:15)
    at Trace.traceCanonical (/Users/atwong/sandbox/alberttwong.github.io/devrelometer/node_modules/systemjs-builder/lib/trace.js:79:15)
    at /Users/atwong/sandbox/alberttwong.github.io/devrelometer/node_modules/systemjs-builder/lib/arithmetic.js:260:33
    at /Users/atwong/sandbox/alberttwong.github.io/devrelometer/node_modules/systemjs-builder/lib/arithmetic.js:249:18
    at Array.reduce (<anonymous>)
    at processExpandedOperations (/Users/atwong/sandbox/alberttwong.github.io/devrelometer/node_modules/systemjs-builder/lib/arithmetic.js:248:33)
    at exports.traceExpression (/Users/atwong/sandbox/alberttwong.github.io/devrelometer/node_modules/systemjs-builder/lib/arithmetic.js:246:6)
    at /Users/atwong/sandbox/alberttwong.github.io/devrelometer/node_modules/systemjs-builder/lib/builder.js:766:14
    at /Users/atwong/sandbox/alberttwong.github.io/devrelometer/node_modules/systemjs-builder/lib/builder.js:765:6
    at processImmediate (internal/timers.js:443:21)
    at Builder.buildStatic (/Users/atwong/sandbox/alberttwong.github.io/devrelometer/node_modules/systemjs-builder/lib/builder.js:760:4)
    at Builder.buildStatic (/Users/atwong/sandbox/alberttwong.github.io/devrelometer/node_modules/jspm/lib/bundle.js:108:48)
    at /Users/atwong/sandbox/alberttwong.github.io/devrelometer/node_modules/jspm/lib/bundle.js:213:26
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
From previous event:
    at /Users/atwong/sandbox/alberttwong.github.io/devrelometer/node_modules/systemjs-builder/lib/trace.js:576:13
From previous event:
    at /Users/atwong/sandbox/alberttwong.github.io/devrelometer/node_modules/systemjs-builder/lib/trace.js:421:6
From previous event:
    at Trace.getLoadRecord (/Users/atwong/sandbox/alberttwong.github.io/devrelometer/node_modules/systemjs-builder/lib/trace.js:151:4)
    at Trace.getAllLoadRecords (/Users/atwong/sandbox/alberttwong.github.io/devrelometer/node_modules/systemjs-builder/lib/trace.js:647:15)
    at Trace.traceCanonical (/Users/atwong/sandbox/alberttwong.github.io/devrelometer/node_modules/systemjs-builder/lib/trace.js:79:15)
    at /Users/atwong/sandbox/alberttwong.github.io/devrelometer/node_modules/systemjs-builder/lib/arithmetic.js:260:33
From previous event:
    at /Users/atwong/sandbox/alberttwong.github.io/devrelometer/node_modules/systemjs-builder/lib/arithmetic.js:249:18
    at Array.reduce (<anonymous>)
    at processExpandedOperations (/Users/atwong/sandbox/alberttwong.github.io/devrelometer/node_modules/systemjs-builder/lib/arithmetic.js:248:33)
From previous event:
    at exports.traceExpression (/Users/atwong/sandbox/alberttwong.github.io/devrelometer/node_modules/systemjs-builder/lib/arithmetic.js:246:6)
    at /Users/atwong/sandbox/alberttwong.github.io/devrelometer/node_modules/systemjs-builder/lib/builder.js:766:14
From previous event:
    at /Users/atwong/sandbox/alberttwong.github.io/devrelometer/node_modules/systemjs-builder/lib/builder.js:765:6
    at processImmediate (internal/timers.js:443:21)
From previous event:
    at Builder.buildStatic (/Users/atwong/sandbox/alberttwong.github.io/devrelometer/node_modules/systemjs-builder/lib/builder.js:760:4)
    at Builder.buildStatic (/Users/atwong/sandbox/alberttwong.github.io/devrelometer/node_modules/jspm/lib/bundle.js:108:48)
    at /Users/atwong/sandbox/alberttwong.github.io/devrelometer/node_modules/jspm/lib/bundle.js:213:26
    at processTicksAndRejections (internal/process/task_queues.js:86:5)

events.js:170
      throw er; // Unhandled 'error' event
      ^
Error: Error on translate for src/main.js at file:///Users/atwong/sandbox/alberttwong.github.io/devrelometer/src/main.js
	(SystemJS) ENOENT: no such file or directory, open '/Users/atwong/sandbox/alberttwong.github.io/devrelometer/jspm_packages/npm/babel-core@5.8.35.js'
	Error: ENOENT: no such file or directory, open '/Users/atwong/sandbox/alberttwong.github.io/devrelometer/jspm_packages/npm/babel-core@5.8.35.js'
	Error loading /Users/atwong/sandbox/alberttwong.github.io/devrelometer/jspm_packages/npm/babel-core@5.8.35.js
	Unable to load transpiler to transpile /Users/atwong/sandbox/alberttwong.github.io/devrelometer/src/main.js
    at /Users/atwong/sandbox/alberttwong.github.io/devrelometer/node_modules/systemjs-builder/lib/trace.js:496:10
    at /Users/atwong/sandbox/alberttwong.github.io/devrelometer/node_modules/systemjs-builder/lib/trace.js:455:8
    at /Users/atwong/sandbox/alberttwong.github.io/devrelometer/node_modules/systemjs-builder/lib/trace.js:421:6
    at Trace.getLoadRecord (/Users/atwong/sandbox/alberttwong.github.io/devrelometer/node_modules/systemjs-builder/lib/trace.js:151:4)
    at Trace.getAllLoadRecords (/Users/atwong/sandbox/alberttwong.github.io/devrelometer/node_modules/systemjs-builder/lib/trace.js:647:15)
    at Trace.traceCanonical (/Users/atwong/sandbox/alberttwong.github.io/devrelometer/node_modules/systemjs-builder/lib/trace.js:79:15)
    at /Users/atwong/sandbox/alberttwong.github.io/devrelometer/node_modules/systemjs-builder/lib/arithmetic.js:260:33
    at /Users/atwong/sandbox/alberttwong.github.io/devrelometer/node_modules/systemjs-builder/lib/arithmetic.js:249:18
    at Array.reduce (<anonymous>)
    at processExpandedOperations (/Users/atwong/sandbox/alberttwong.github.io/devrelometer/node_modules/systemjs-builder/lib/arithmetic.js:248:33)
    at exports.traceExpression (/Users/atwong/sandbox/alberttwong.github.io/devrelometer/node_modules/systemjs-builder/lib/arithmetic.js:246:6)
    at /Users/atwong/sandbox/alberttwong.github.io/devrelometer/node_modules/systemjs-builder/lib/builder.js:766:14
    at /Users/atwong/sandbox/alberttwong.github.io/devrelometer/node_modules/systemjs-builder/lib/builder.js:765:6
    at processImmediate (internal/timers.js:443:21)
    at Builder.buildStatic (/Users/atwong/sandbox/alberttwong.github.io/devrelometer/node_modules/systemjs-builder/lib/builder.js:760:4)
    at Builder.buildStatic (/Users/atwong/sandbox/alberttwong.github.io/devrelometer/node_modules/jspm/lib/bundle.js:108:48)
    at /Users/atwong/sandbox/alberttwong.github.io/devrelometer/node_modules/jspm/lib/bundle.js:213:26
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
From previous event:
    at /Users/atwong/sandbox/alberttwong.github.io/devrelometer/node_modules/systemjs-builder/lib/trace.js:576:13
From previous event:
    at /Users/atwong/sandbox/alberttwong.github.io/devrelometer/node_modules/systemjs-builder/lib/trace.js:421:6
From previous event:
    at Trace.getLoadRecord (/Users/atwong/sandbox/alberttwong.github.io/devrelometer/node_modules/systemjs-builder/lib/trace.js:151:4)
    at Trace.getAllLoadRecords (/Users/atwong/sandbox/alberttwong.github.io/devrelometer/node_modules/systemjs-builder/lib/trace.js:647:15)
    at Trace.traceCanonical (/Users/atwong/sandbox/alberttwong.github.io/devrelometer/node_modules/systemjs-builder/lib/trace.js:79:15)
    at /Users/atwong/sandbox/alberttwong.github.io/devrelometer/node_modules/systemjs-builder/lib/arithmetic.js:260:33
From previous event:
    at /Users/atwong/sandbox/alberttwong.github.io/devrelometer/node_modules/systemjs-builder/lib/arithmetic.js:249:18
    at Array.reduce (<anonymous>)
    at processExpandedOperations (/Users/atwong/sandbox/alberttwong.github.io/devrelometer/node_modules/systemjs-builder/lib/arithmetic.js:248:33)
From previous event:
    at exports.traceExpression (/Users/atwong/sandbox/alberttwong.github.io/devrelometer/node_modules/systemjs-builder/lib/arithmetic.js:246:6)
    at /Users/atwong/sandbox/alberttwong.github.io/devrelometer/node_modules/systemjs-builder/lib/builder.js:766:14
From previous event:
    at /Users/atwong/sandbox/alberttwong.github.io/devrelometer/node_modules/systemjs-builder/lib/builder.js:765:6
    at processImmediate (internal/timers.js:443:21)
From previous event:
    at Builder.buildStatic (/Users/atwong/sandbox/alberttwong.github.io/devrelometer/node_modules/systemjs-builder/lib/builder.js:760:4)
    at Builder.buildStatic (/Users/atwong/sandbox/alberttwong.github.io/devrelometer/node_modules/jspm/lib/bundle.js:108:48)
    at /Users/atwong/sandbox/alberttwong.github.io/devrelometer/node_modules/jspm/lib/bundle.js:213:26
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
Emitted 'error' event at:
    at DestroyableTransform.onerror (/Users/atwong/sandbox/alberttwong.github.io/devrelometer/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:558:12)
    at DestroyableTransform.emit (events.js:193:13)
    at Timeout._onTimeout (/Users/atwong/sandbox/alberttwong.github.io/devrelometer/node_modules/gulp-jspm/index.js:51:22)
    at listOnTimeout (internal/timers.js:535:17)
    at processTimers (internal/timers.js:479:7)
```
